--
title: "Rating update"
output: html_notebook
---

## ratings arranged in order of recency 

packages & functions

```{r}
library(tidyverse)
library(lubridate)
source("recency_functions.R")
```


get games and league IDs

```{r}
games=readRDS("~/teaching/scoresway/rds/games.rds")
(league_ids=readRDS("league_ids.rds"))
```



get last played date: see what happens for leagues with no games played yet when I get some unplayed games in the database



```{r}
league_ids %>% arrange(the_country) %>% mutate(row=row_number()) %>% select(the_country, row, id) -> li
tz="America/Toronto"
last_posterior_date() %>% separate(fname,into=c("league","rest"),extra="merge",sep=".(?=[^_]+$)") %>% 
  mutate(league=str_to_title(league)) %>% 
  left_join(li,by=c("league"="the_country")) %>% 
  mutate(iso_week_lr=iso_week_half(mtime)) %>% 
  mutate(last_game=map_dbl(id,~last_game_date(games,.))) %>% 
  mutate(last_game=as_datetime(last_game,tz=tz)) %>% 
  mutate(iso_week_last=iso_week_half(last_game)) %>% 
  mutate(next_ungotten=map_dbl(id, ~last_ungotten(games, .))) %>% 
  mutate(next_ungotten_future=map_dbl(id, ~last_ungotten(games, ., after_now=T))) %>%
  mutate(next_ungotten=as_datetime(next_ungotten,tz=tz)) %>% 
  mutate(next_ungotten_future=as_datetime(next_ungotten_future,tz=tz)) %>%
  mutate(iso_week_next=iso_week_half(next_ungotten)) %>% 
  mutate(iso_week_future=iso_week_half(next_ungotten_future)) %>%
  mutate(since_rating=(last_game-mtime)/dhours(1)) %>% 
  mutate(ug_from_now=(next_ungotten-Sys.time())/dhours(1)) %>% 
  mutate(action=case_when(
    ug_from_now< (-2.1) ~ "get games",
    ug_from_now<0 ~ "more",
    since_rating<0 ~ "z",
    iso_week_next>iso_week_last ~ "a new rating",
    TRUE ~ "more coming later"
  )) %>% 
  mutate(games_since_rating=last_game>mtime) %>% 
  mutate(next_v_future=ifelse(iso_week_future>iso_week_next, "get now ------->", "wait")) %>% 
  mutate(now=now()) %>% 
  arrange(action, next_ungotten) %>% 
  drop_na() %>% 
  select(league, last_rating=mtime, iso_week_lr, last_game, iso_week_last, next_ungotten, iso_week_next, next_ungotten_future, iso_week_future, row, action, games_since_rating, next_v_future, now) %>% View("action")
```







